name: TagBot
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.JLPKGBUTLER_TOKEN }}
          branches: true
$[[#include_custom_registry]]
          registry: $[[{JL_CUSTOM_REGISTRY}]]
$[[/include_custom_registry]]
